// producation record types
// const RECORD_TYPES = {
//   AGRI_EXPERT: '0125g0000010H5bAAE',
//   FARMER: '0125g0000010H5cAAE',
//   RETAILER: '0125g0000010H4KAAU',
//   DISTRIBUTOR: '0125g0000010FubAAE',
//   DEMO_FIELD_DAY: '0125g0000010H4QAAU',
//   BALLOON_SHOW: '0125g0000010H4LAAU',
//   DEMO_ACTIVITY: '0125g0000010H4MAAU',
//   NORMAL_DEMO_ACTIVITY: '0125g0000010Jf2AAE',
//   NEW_PRODUCT_TRAILS: '0125g0000010H4TAAU',
//   KVK_VISIT: '0125g0000010H4RAAU',
//   FARMER_MEETING: '0125g0000010H4PAAU',
//   VAN_CAMPAIGN: '0125g0000010H4VAAU',
//   OUT_STATION: '0125g0000010HA7AAM',
//   LOCAL: '0125g0000010H4WAAU',
//   KRISHI_MELA: '0125g0000010H4SAAU',
//   AGRI_EXPERT_VISIT: '0125g0000010H4XAAU',
//   DISTRIBUTOR_VISIT: '0125g0000010H4YAAU',
//   RETAILER_VISIT: '0125g0000010H4aAAE',
//   FARMER_VISIT: '0125g0000010H4ZAAU',
//   DEMO_LPD_ACTIVITY: '0125g0000010H4NAAU',
//   OTHRE_ACTIVITY: '0125g0000010H4UAAU',
//   DEMO_OBSERVATION_DAY: '0125g0000010H4OAAU',
//   OTHER_STATE_SFID:"a015g00000udnj8AAA",
//   OTHER_DISTRICT_SFID:"a025g00000H9Ep3AAF",
//   OTHER_SUB_DISTRICT_SFID:"a035g00000Hgb4XAAR",
//   OTHER_VILLAGE_SFID:"a055g00000Aetu3AAB",
// };

// staging record types
// const RECORD_TYPES = {
//   AGRI_EXPERT: '0120p000001ogTxAAI',
//   FARMER: '0120p000001ogTyAAI',
//   RETAILER: '0120p000001ogTkAAI',
//   DISTRIBUTOR: '0120p000001ogTZAAY',
//   DEMO_FIELD_DAY: '0120p000001ogTpAAI',
//   DEMO_ACTIVITY: '0120p000001ogTmAAI',
//   NORMAL_DEMO_ACTIVITY: '0120p00000226i1AAA',
//   NEW_PRODUCT_TRAILS: '0120p000001ogTsAAI',
//   BALLOON_SHOW: '0120p000001ogTlAAI',
//   KVK_VISIT: '0120p000001ogTqAAI',
//   FARMER_MEETING: '0120p000001ogToAAI',
//   VAN_CAMPAIGN: '0120p000001ogTuAAI',
//   OUT_STATION: '0120p000001ogTwAAI',
//   LOCAL: '0120p000001ogTvAAI',
//   KRISHI_MELA: '0120p000001ogTrAAI',
//   AGRI_EXPERT_VISIT: '0120p000001ogTzAAI',
//   DISTRIBUTOR_VISIT: '0120p000001ogU0AAI',
//   RETAILER_VISIT: '0120p000001ogU2AAI',
//   FARMER_VISIT: '0120p000001ogU1AAI',
//   DEMO_LPD_ACTIVITY: '0120p000001ogTnAAI',
//   OTHRE_ACTIVITY: '0120p000001ogTtAAI',
//   DEMO_OBSERVATION_DAY: '0120p00000221LdAAI',
// };
//companies name
const COMPANIES = [
  'UPL LTD.',
  'PI INDUSTRIES',
  'SUMITOMO CHEMICALS',
  'GHARDA GROUP',
  'BAYER CROP SCIENCE',
  'BHARAT RASAYAN',
  'INDIA PESTICIDES',
  'SHIVALIK RASAYAN',
  'SHARDA CROP CHEM',
  'TAGROS CHEMICALS',
  'COROMANDAL INTERNATIONAL',
  'MEGHMANI GROUP',
  'BHARAT GROUP',
  'INDOFIL INDUSTRIES',
  'CRYSTAL CROP PROTECTION',
  'KRISHI RASAYAN',
  'RALLIS INDIA',
  'WILLOWOOD CHEMICALS',
  'SML GROUP',
  'NACL INDUSTRIES',
  'BEST AGROLIFE',
  'INSECTICIDES INDIA LIMITED',
  'DHANUKA AGRITECH',
  'HERANBA INDUSTRIES',
  'GSP CROP SCIENCE',
  'DHARMAJ CROP',
  'KILPEST INDIA',
  'SIKKO INDUSTRIES',
  'AIMCO PESTICIDES',
  'ARISTO BIO-TECH.',
  'SUPER CROP SAFE',
  'PHYTO CHEM',
  'ASTEC LIFE',
  'FINE ORGANICS',
  'EXCEL INDUSTRIES',
  'PUNJAB CHEMICALS',
  'JUBILANT INDUSTRIES',
  'NAGARJUNA',
  'PAUSHAK',
  'INDOGULF CROP SCIENCE',
];
//AGRI EXPERT TYPE
const AGRI_EXPERT_TYPE = {
  INFLUENCER: 'Influencer',
  GOVT_DEPT: 'Govt. deptt.',
  COMPETITOR_EMPLOYEES: 'Competitor employee',
  COMPETITOR_DISTRIBUTOR: 'Competitor distributor',
};


// development record types
const RECORD_TYPES = {
  AGRI_EXPERT: "012N0000003hytxIAA",
  FARMER: "012N0000003UEuzIAG",
  RETAILER: "012N0000003UCEMIA4",
  DISTRIBUTOR: "012N0000003UCERIA4",
  DEMO_FIELD_DAY: "012N0000003hsYCIAY",
  DEMO_ACTIVITY: "012N0000003hsY7IAI",
  NORMAL_DEMO_ACTIVITY: "012Hy000003aRZHIA2",
  NEW_PRODUCT_TRAILS: "012N0000003hsY2IAI",
  BALLOON_SHOW: "012N0000003hsXxIAI",
  KVK_VISIT: "012N0000003hsXsIAI",
  FARMER_MEETING: "012N0000003hsXnIAI",
  VAN_CAMPAIGN: "012N0000003hsXiIAI",
  OUT_STATION: "012N0000003Vil5IAC",
  LOCAL: "012N0000003Vil0IAC",
  KRISHI_MELA: "012N0000003iXgeIAE",
  AGRI_EXPERT_VISIT: "012N0000003ia44IAA",
  DISTRIBUTOR_VISIT: "012N0000003ia3zIAA",
  RETAILER_VISIT: "012N0000003ia3pIAA",
  FARMER_VISIT: "012N0000003ia3kIAA",
  DEMO_LPD_ACTIVITY: "012N0000003iiUxIAI",
  OTHRE_ACTIVITY: "012N0000003vZLVIA2",
  DEMO_OBSERVATION_DAY: "012N0000003wKRdIAM",
  OTHER_STATE_SFID: "a09Hy00000SjfAnIAJ",
  OTHER_DISTRICT_SFID: "a0AHy000008ScKKMA0",
  OTHER_SUB_DISTRICT_SFID: "a0BHy000008jKigMAE",
  OTHER_VILLAGE_SFID: "a0CHy000009Xfh4MAC",
};

//  ----------------------- schema starts here --------------------
const SCHEMA = {
  SALESFORCE: {
    USER: "salesforce.user__c",
    ATTENDANCE: "salesforce.attendance__c",
    RECORDTYPE: "salesforce.recordtype",
    ACCOUNT: "salesforce.account",
    STATE__C: "salesforce.state__c",
    DISTRICT__C: "salesforce.district__c",
    SUB_DISTRICT__C: "salesforce.sub_district__c",
    VILLAGE__C: "salesforce.village__c",
    CROP__C: "salesforce.crop__c",
    EVENT__C: "salesforce.event__c",
    APPROVAL__C: "salesforce.approval__c",
    CONTACT: "salesforce.contact",
    PRODUCT2: "salesforce.product2",
    PRICEBOOKENTRY: "salesforce.pricebookentry",
    VISIT__C: "salesforce.visit__c",
    FILE__C: "salesforce.file__c",
    NEW_PRODUCT__C: "salesforce.new_product__c",
    DISTRIBUTOR_LIST: "salesforce.distributor_retailer__c",
    New_Retailer__c: "salesforce.New_Retailer__c",
    NEW_FARMER__C: "salesforce.new_farmer__c",
    FEEDBACK__C: "salesforce.feedback__c",
    EXPENSE_LINE: "salesforce.Expense_Line_Item__c",
    HR_Policy__c: "salesforce.HR_Policy__c",
    ORDER: "salesforce.Order",
    ORDER_ITEM: "salesforce.OrderItem",
    Target_Vs_Achievement__c: "salesforce.Target_Vs_Achievement__c",
    INVOICE__C: "salesforce.Invoice__c",
    INVOICE_LINE_ITEM__C: "salesforce.Invoice_Line_Item__c",
    PRICEBOOK2: "salesforce.Pricebook2",
    TERRITORY__C: "salesforce.Territory__c",
    VAN_CAMPAIGN_VILLAGE__C: "salesforce.Van_Campaign_Village__c",
    Detail_of_Proprietor__c: "salesforce.Detail_of_Proprietor__c",
    Retail_of_Business__c: "salesforce.Retail_of_Business__c",
    Product_of_Interest__c: "salesforce.Product_of_Interest__c",
    Sister_Company__c: "salesforce.Sister_Company__c",
    Plant_Master__c: "salesforce.Plant_Master__c",
    Inventory__c: "salesforce.Inventory__c",
    LEADERBOARD__C: "salesforce.Leader_Board__c",
    LEDGER__C: "salesforce.Ledger__c",
    ANNOUNCEMENT__c: "salesforce.Announcement__c",
  },
  PUBLIC: {
    USER: 'public."_User"',
    SESSION: 'public."_Session"',
    PICKLIST_CATEGORIES: 'public."picklistcategories"',
    PICKLISTS: 'public."picklists"',
    NOITIFICATIONS: 'public."Notifications"',
    USER:'public."_User"'
  },
};
//  ----------------------- schema ends here --------------------

// ----------------------- all fields name starts here --------------------
const OBJECTKEYNAME = {
  ACTIVE: "active__c",
  MOBILE__C: "mobile__c",
  Phone__c: "phone__c",
  Telephone__c: "Telephone__c",
  Is_Mobile_Linked__c: "Is_this_Mobile_number_linked_with_Aadhaa__c",
  Is_Mobile_Whatsapp__c: "Is_this_a_WhatsApp_Number__c",
  Alternate_Mobile__c: "Alternate_Mobile__c",
  Establishment_Year__c: "Establishment_Year__c",
  Business_Type__c: "Type_of_Business__c",
  Shop_Office__c: "Shop_Office__c",
  Godown_Area__c: "Area_Of_Godown_Sq_Feet__c",
  Godown_Facility__c: "Godown_Facility__c",
  Total_Employees__c: "NumberOfEmployees",
  Total_Vehicles__c: "No_of_Vehicles__c",
  GSTIN_Registration_Date__c: "GSTIN_Registration_Date__c",
  GSTIN_Registration_Date__c: "GSTIN_Registration_Date__c",
  PROFILE__C: "profile__c",
  Result__c: "Result__c",
  Product_superiority_over_competition__c:
    "Product_superiority_over_competition__c",
  First_Mobile__c: "First_Mobile__c",
  Last_Visit_Brand: "Last_Visit_Brand__c",
  SFID: "sfid",
  USER__C: "user__c",
  DATE__C: "date__c",
  Bank_Name__c: "Bank_Name__c",
  Bankers_Name__c: "Banker_s_Name__c",
  Bankers_Address__c: "Banker_Addresss__c",
  Cash_Credit_Limit__c: "Credit_Limit__c",
  Deposit_Others__c: "Others_Security_Deposite_Detai__c",
  Pesticides__c: "Pesticides__c",
  Fertilizers__c: "Fertilizers__c",
  Seeds__c: "Seeds__c",
  Product_Others__c: "Others_Product_Turnover__c",
  Is_Income_Tax_Assessee: "Is_your_firm_Income_Tax_Assessee__c",
  Total_Annual_Turnover__c: "Total_Annual_Turnover_in_Lacs_IIL__c",
  Capital_Employed__c: "Capital_Employed__c",
  Annual_Income__c: "Annual_Income__c",
  Expected_IIL_Investment__c: "Expected_Investment_in_IIL__c",
  Expected_1_Year_Turnover_With_IIL_c:
    "Expected_Turnover_in_1st_Year_with_IIL__c",
  Expected_Next_Year_Turnover_With_IIL_c:
    "Expected_Turnover_in_next_Year_with_IIL__c",
  Proposed_Payment_Terms: "Proposed_Payment_Terms_in_days__c",
  Payment_Credit_Limit__c: "Credit_Limit_Required_Specify_Amount_in__c",
  Total_Retailers__c: "Total_No_of_Retailers__c",
  Total_Districts_Covered__c: "No_of_Districts_Covered__c",
  Total_Villages_Covered__c: "No_of_Village_Covered__c",
  Area_Specification__c: "Specify_Area__c",
  Major_Crops__c: "Major_Crops__c",
  Dealer_Credit__c: "Rs_In_Lacs__c",
  Dealer_Credit_Days__c: "No_of_Credit_Days__c",
  Transporter_Name_1__c: "Name_of_Transporter_1__c",
  Transporter_Name_2__c: "Name_of_Transporter_2__c",
  Transporter_Name_3__c: "Name_of_Transporter_3__c",
  Material_Dispatch_Destination__c: "Destination_of_Dipatch_of_Material__c",
  Depot_Distance__c: "Distance_from_depot__c",
  Other_Dealer_Info__c: "Any_Other_detail_Info_about__c",
  Party_Credibility__c: "Credibility_of_Party__c",
  Is_Party_Visited_Personally__c: "Have_you_visited_the_Party_Personally__c",
  GST_Registration_Certificate_Image__c: "GST_Registration_Certificate__c",
  Distributor_Request_Letter_Image__c:
    "Distributorship_Request_Letter_on_Custom__c",
  Fertilizer_License_Image__c: "Pesticides_License__c",
  Amount__c: "Amount_INR__c",
  Amount_For_Order__c: "Amount__c",
  NAME__C: "name__c",
  NAME: "name",
  Agri_inputs_exp_per_acre: "agri_inputs_exp_per_acre",
  FARMER_NAME__C: "farmer_name__c",
  FATHER_NAME__C: "father_name__c",
  Farmer_Category__c: "Farmer_Category__c",
  Farmer_Range__c: "Farmer_Range__c",
  Retailer_Range__c: "Retailer_Range__c",
  FO_NAME__C: "FO_Name__c",
  EMAIL__C: "email__c",
  Hierarchy_Level__C: "hierarchy_level__c",
  TOTAL_CROP_ACREAGE__C: "total_crop_acreage__c",
  ARE_YOU_ON_FIELD__C: "are_you_on_field__c",
  STATE__C: "state__c",
  Other_State__c: "Other_State__c",
  State_LPD__c: "State_LPD__c",
  NAME_TAG: "name_tag",
  DISTRICT__C: "district__c",
  Other_District__c: "Other_District__c",
  District_LPD__c: "District_LPD__c",
  SUB_DISTRICT__C: "sub_district__c",
  Others_Sub_District__c: "Others_Sub_District__c",
  Name_Of_Department__c: "Name_Of_Department__c",
  Sub_District_LPD__c: "Sub_District_LPD__c",
  CITY__C: "city__c",
  MANDALS_TEHSIL_TALUKA__C: "mandals_tehsil_taluka__c",
  VILLAGE__C: "village__c",
  Other_Village__c: "Other_Village__c",
  Village_LPD__c: "Village_LPD__c",
  Product_demoLPD__c: "Product_demoLPD__c",
  VILLAGE__NAME: "village_name",
  METHOD__C: "method__c",
  FROM_WHERE__C: "from_where__c",
  ADVICE_FROM_INFLUENCER__C: "advice_from_influencer__c",
  PICTURE__C: "picture__c",
  AADHAR_NUMBER__C: "aadhar_number__c",
  DATE_OF_BIRTH__C: "date_of_birth__c",
  NUMBER_OF_FIELDS__C: "number_of_fields__c",
  RECORD_TYPE: "RecordTypeId",
  LAST_NAME: "lastname",
  AT_THE_SHOP__C: "at_the_shop__c",
  ADDRESS__C: "address__c",
  OWNER__C: "owner__c",
  OWNER__ID: "ownerid",
  DESIGNATION_PROFILE__C: "designation_profile__c",
  TYPE_OF_AGRI_EXPERT__C: "type_of_agri_expert__c",
  categoryid: " categoryid",
  CATEGORIEID: "categoryid",
  STATE_NAME__C: "state_name__c",
  DISTRICT_NAME__C: "district_name__c",
  SUB_DISTRICT_NAME__C: "sub_district_name__c",
  TEAM__C: "team__c",
  BUSINESS_UNIT__C: "business_unit__c",
  OUT_TIME__C: "out_time__c",
  IN_TIME__C: "in_time__c",
  DESCRIPTION__C: "description__c",
  EFFECTIVE_HOURS__C: "effective_hours__c",
  LOCATION__C: "location__c",
  TOTAL_HOURS__C: "total_hours__c",
  PREMISE_NAME_IN__C: "premise_name_in__c",
  ACTIVITY_TYPE__C: "activity_type__c",
  PREMISE_NAME_OUT__C: "premise_name_out__c",
  ATTENDANCE_STATUS: "attendance_status__c",
  ACREAGE__C: "acreage__c",
  NAME_OF_RETAILER_1__C: "Name_of_Retailer_1__c",
  NAME_OF_RETAILER_2__C: "Name_of_Rertailer_2__c",
  NAME_OF_RETAILER_3__C: "Name_of_Rertailer_3__c",
  NAME_OF_RETAILER_1__C_ID: "Name_of_Retailer_1__c_id",
  NAME_OF_RETAILER_2__C_ID: "Name_of_Rertailer_2__c_id",
  NAME_OF_RETAILER_3__C_ID: "Name_of_Rertailer_3__c_id",
  OTHER_1: "Others_1__c",
  OTHER_2: "Others_2__c",
  OTHER_3: "Others_3__c",
  INFLUENCER_NAME__C: "influencer_name_agriexpert__c",
  OTHER_AGRIEXPERT__C: "other_agriexpert__c",
  INFLUENCER_MOBILE__C: "influencer_mob_no__c",
  ID_TYPE__C: "id_type__c",
  PROFILE_PICTURE__C: "profile_picture__c",
  Irrigation__c: "Irrigation__c",
  Other_Irrigation_Method__c: "Other_Irrigation_Method__c",
  VILLAGE_NAME__C: "village_name__c",
  PINCODE__C: "pincode__c",
  SEASON__C: "season__c",
  IRRIGATION_METHOD__C: "irrigation_method__c",
  CROP__C: "crop__c",
  Firm_Name__c: "Firm_Name__c",
  Prop_Parternership__c: "Prop_Parternership__c",
  Total_Annual_Turnover_in_Lacs_IIL__c: "Total_Annual_Turnover_in_Lacs_IIL__c",
  Company_1_Brand__c: "company_1_brand__c",
  Company_2_Brand__c: "company_2_brand__c",
  Company_3_Brand__c: "company_3_brand__c",
  Company_4_Brand__c: "company_4_brand__c",
  Company_5_Brand__c: "company_5_brand__c",
  Brands_Promoted__c: "Brands_Promoted__c",
  No_of_Retailers__c: "No_of_Retailers__c",
  Working_With__c: "Working_With__c",
  Territory_Looking__c: "Territory_Looking__c",
  No_of_Distributors__c: "No_of_Distributors__c",
  Business_Value__c: "Business_Value__c",
  Experience__c: "Experience__c",
  No_of_Farmers_associated_with_him__c: "No_of_Farmers_associated_with_him__c",
  ACREAGES__C: "acreages__c",
  AgriInputs_Exp_per_Acre__c: "AgriInputs_Exp_per_Acre__c",
  ACCOUNT__C: "account__c",
  ID: "id",
  RETAILER_SHOP_NAME__C: "retailer_shop_name__c",
  CONTACT_PERSON__C: "contact_person__c",
  CONTACT_PERSON_DESIGNATION__C: "contact_person_designation__c",
  PAN_NO__C: "pan_no__c",
  GSTIN_NO__C: "gstin_no__c",
  GSTIN_APPLIED__C: 'GSTIN_applied__c',
  GST_NUMBER__C: "gst_number__c",
  PESTICIDE_FERTILIZER_LICENSE__C: "pesticide_fertilizer_license__c",
  LICENSE_NUMBER__C: "license_number__c",
  PESTICIDE_LICENSE_EXPIRY_DATE__C: "pesticide_license_expiry_date__c",
  PREFERRED_DISTRIBUTOR__C: "preferred_distributor__c",
  SECOND_PREFERRED_DISTRIBUTOR__C: "second_preferred_distributor__c",
  PRICE_GROUP__C: "Price_Group__c",
  PRICE_UNIT__C: "Price_Unit__c",
  IS_RETAILER_A_FARMER__C: "is_retailer_a_farmer__c",
  PESTICIDE_LICENSE__C: "pesticides_license__c",
  RETAILER_CATEGORY__C: "retailer_category__c",
  IIL_CATEGORY__C: "iil_category__c",
  AGRI_IMPLIMENTS_TURNOVER__C: "agri_implements_turnover__c",
  PESTICIDE_SALE__C: "pesticide_sale__c",
  SEED_SALES__C: "seed_sales__c",
  FERTILIZE_SALLES__C: "fertilizer_salles__c",
  IIL_BUSINESS__C: "iil_business__c",
  HEROKU_ID__C: "heroku_id__c",
  Heroku_ID__c: "Heroku_ID__c",
  ACCOUNT__HEROKU_ID__C: "Account__Heroku_ID__c",
  PRODUCT__C: "product__c",
  OTHER_PRODUCT__C: "Other_Product__c",
  TANK_MIX__C: "Tank_Mix__c",
  Observation_period__c: "Observation_period__c",
  Observation_day__c: "Observation_day__c",
  Post_Harvest_Observation__c: "Post_Harvest_Observation__c",
  Qty__c: "Qty__c",
  NAME_OF_CROP__C: "name_of_crop__c",
  SELECT_MARKET__C: "select_market__c",
  Product_Plan_A__c: "product_plan_a__c",
  Product_Plan_B__c: "product_plan_b__c",
  Product_Plan_C__c: "product_plan_c__c",
  Product_Plan_Unit_A__c: "product_plan_Unit_a__c",
  Product_Plan_Unit_B__c: "product_plan_unit_b__c",
  Product_Plan_Unit_C__c: "product_plan_unit_c__c",
  NAME_OF_DISTRIBUTORS__C: "name_of_distributors__c",
  DEMO_START_DATE__C: "demo_start_date__c",
  DEMO_END_DATE__C: "demo_end_date__c",
  DEMO_ACTIVITY_TYPE: "demo_activity_type__c",
  CONCERNED_TERRITORY_HEAD__C: "concerned_territory_head__c",
  PRODUCT_QUANTITY_PLAN_A__C: "product_quantity_plan_a__c",
  PRODUCT_QUANTITY_PLAN_B__C: "product_quantity_plan_b__c",
  PRODUCT_QUANTITY_PLAN_C__C: "product_quantity_plan_c__c",
  NUMBER_OF_DAYS__C: "number_of_days__c",
  TEAM_LEADER__C: "team_leader__c",
  NUMBER_OF_FARMERS_COVERED__C: "number_of_farmers_covered__c",
  Number_of_village_covered__c: "Number_of_village_covered__c",
  Select_Visited_by__c: "Select_Visited_by__c",
  Field_Rating_for_demo_given_by_farmer__c:
    "Field_Rating_for_demo_given_by_farmer__c",
  ACREAGE_COVERED__C: "acreage_covered__c",
  DISTRICTS__C: "districts__c",
  PRODUCT_QUANTITY__C: "product_quantity__c",
  FERT_LICENSE_NO__C: "fert_lic_no__c",
  FERT_LIC_Registration_Date__c: "Fertilizer_Lic_No_Registration_Date__c",
  FERT_LIC_Registration_Validity__c: "Fertilizer_Lic_No_Valid_Upto__c",
  DD_Cheque_Online_Ref_No__c: "DD_Cheque_Online_Ref_No__c",
  INST_LICENSE_NO__C: "inst_lic_no__c",
  INST_LIC_Registration_Date__c: "Insecticides_Lic_No_Registration_Date__c",
  INST_LIC_Registration_Validity__c: "Insecticides_Lic_No_Valid_Upto__c",
  CUSTOMER_NO__C: "customer_no__c",
  SALES_ORG__C: "sales_org__c",
  DISTRIBUTION_CHANNEL__C: "distribution_channel__c",
  DIVISION__C: "division__c",
  CUSTOMER__C: "Customer__c",
  CUSTOMER_GROUP__C: "customer_group__c",
  SALES_OFFICE__C: "sales_office__c",
  CURRENCY__C: "currency__c",
  PRICE_GROUP__C: "price_group__c",
  CUST_PRICE_PRO__C: "cust_pric_Pro__c",
  CREDIT_LIMIT__C: "credit_limit__c",
  COMPANY_1_BRAND__C: "company_1_brand__c",
  FERTILIZERS_TURNOVER__C: "fertilizers_turnover__c",
  SEEDS_OTHER_TURNOVER__C: "seeds_other_turnover__c",
  PESTICIDE_TURNOVER__C: "Pesticide_turnover__c",
  TOTAL_ANNUAL_TURNOVER_IN_LAC_IIL__C: "total_annual_turnover_in_lacs_iil__c",
  TOTAL_RETAIL_TURNOVER__C: "total_retail_turnover__c",
  PRICE_LIST__C: "price_List__c",
  PAYMENT_TERMS__C: "payment_terms__c",
  WAKON__C: "wakon__c",
  DUNNING__C: "dunning__c",
  RECONCILIATION__C: "reconciliation__c",
  DELIVERY__C: "delivery__c",
  PLANT__C: "plant__c",
  SHIPPING_CONDITION__C: "shipping_condition__c",
  INCO_TERM__C: "inco_term__c",
  A_C_ASSIGN_GROUP__C: "a_c_assign_group__c",
  JOC_G__C: "joc_g__c",
  Z1_TO_Z8__C: "z1_to_z8__c",
  SALES_RIGISTRATION__C: "sales_registration__c",
  BRAND__C: "brand__c",
  OTHER_BRAND__C: "Other_Brand__c",
  PRODUCT_ID__C: "Product_id__c",
  PRODUCT_INTERESTED__C: "Product_interested__c",
  FEEDBACK__C: "Feedback__c",
  BRAND_WISE_ANNUAL_TURNOVER_IN_LACS_C: "brand_wise_annual_turnover_in_Lacs__c",
  POSTAL_CODE__C: "postal_code__c",
  FAX__C: "fax__c",
  CATEGORY__C: "Category__c",
  BP_GROUP__C: "bp_group__c",
  BP_NUMBER__C: "bp_number__c",
  NATURE_OF_FIRMS__C: "Nature_of_Frims__c",
  Other_NATURE_OF_FIRMS__C: 'other_nature_of_firms__c',
  COMPANY__C: "company__c",
  COUNTRY__C: "county__c",
  APPLIED_FOR_DISTRIBUTORSHIP__C: "applied_for_distributorship__c",
  TYPE_OF_FARMER_MEET__C: "type_of_farmer_meet__c",
  SALES_OFFICER_MDO__C: "Sales_Officer_MDO__c",
  SALES_REPRESENTATIVE_MDR__C: "sales_representative_mdr__c",
  AREA_SALES_MANAGER_MDM__C: "area_sales_manager_mdm__c",
  CROP_ADVISOR__C: "crop_advisor__c",
  ASSIGNED_TO__C: "Assigned_to__c",
  NAME_OF_KVK__C: "Name_of_KVK__c",
  NAME_OF_SCIENTIST__C: "Name_of_Scientist__c",
  DISCUSSION__C: "Discussion__c",
  FOLLOW_UP__C: "Follow_up__c",
  STAFF_NAME__C: "Staff_name__c",
  MobilePhone: "MobilePhone",
  FirstName: "FirstName",
  LastName: "LastName",
  Contact__Heroku_ID__c: "Contact__Heroku_ID__c",
  DEMO_DATE__C: "demo_date__c",
  PEST_NAME__C: "pest_name__c",
  PEST_TYPE__C: "pest_type__c",
  PLOT_NAME_C: "plot_name__c",
  UNIT__C: "unit__c",
  UnitPrice: "unitprice",
  ListPrice: "listprice",
  COMMENT__C: "Comment__c",
  EVENT_STAUS__C: "Event_Status__c",
  Z1__C: "z1__c",
  Z2__C: "z2__c",
  Z3__C: "z3_c",
  Z4__C: "z4__c",
  Z5__C: "z5__c",
  Z6__C: "z6__c",
  Z7__C: "z7__c",
  Z8__C: "z8__c",
  Z1: "Z1",
  Z2: "Z2",
  Z3: "Z3",
  Z4: "Z4",
  Z5: "Z5",
  Z6: "Z6",
  Z7: "Z7",
  Z8: "Z8",
  Z9: "Z9",
  Z10: "Z10",
  LEVEL_1: "Level 1",
  LEVEL_2: "Level 2",
  LEVEL_3: "Level 3",
  LEVEL_4: "Level 4",
  LEVEL_5: "Level 5",
  LEVEL_6: "Level 6",
  LEVEL_7: "Level 7",
  LEVEL_8: "Level 8",
  LEVEL_9: "Level 9",
  LEVEL_10: "Level 10",
  EVENT_STATUS__C: "Event_Status__C",
  MOBILE_NUMBER__C: "Mobile_number__c",
  PESTICIDES_LICENSE_NUMBER__C: "Pesticides_License_Number__c",
  LAST_VISIT_DATE__C: "Last_Visit_Date__c",
  AT_SHOP__C: "At_Shop__c",
  HIGH_MOVING_IIL_PRODUCTS__C: "High_moving_IIL_products__c",
  COMMENTS__C: "Comments__c",
  Rejection_Level__c: "Rejection_Level__c",
  EVENT__C__HEROKU_ID__C: "Event__c__Heroku_ID__c",
  DISTRIBUTOR_SHOP_NAME__C: "Distributor_Shop_Name__c",
  CURRENT_INVENTORIES__C: "Current_Inventories__c",
  MARKET_INSIGHTS__C: "Market_Insights__c",
  COLLECTION_TARGET_DISCUSSION__C: "Collection_Target_Discussion__c",
  SALES_TARGET_DISCUSSION__C: "Sales_Target_Discussion__c",
  FOCUS_PRODUCT_DISCUSSION__C: "Focus_Product_Discussion__c",
  MARKET_DEVELOPMENT__C: "Market_Development__c",
  DISTRIBUTOR_FEEDBACK__C: "Distributor_Feedback__c",
  COMPLAINT_ISSUES__C: "Complaint_Issues__c",
  DISTRIBUTOR_NAME__C: "Distributor_Name__c",
  Invoice_Date__c: "Invoice_Date__c",
  Invoice_Serial_No__c: "invoice_serial_no__c",
  EVENT__C: "Event__c",
  QUANTITY__C: "Quantity__c",
  VISIT__C__HEROKU_ID__C: "Visit__c__Heroku_ID__c",
  AREA_MANAGER__C: "Area_Manager__c",
  RECORD_TYPE_ID: "recordtypeid",
  FA_NAME__C: "FA_Name__c",
  Name_of_Villlage__c: "Name_of_Villlage__c",
  NAME_OF_PEST__C: "Name_of_Pest__c",
  PRODUCTNAME__C: "ProductName__c",
  AREA_OF_TRIAL__C: "Area_of_Trial__c",
  DOSES__C: "Doses__c",
  DOSE_PER_ACRE_C: "Dose_per_Acre__c",
  SALES_POTENTIAL_OF_VILLAGE__C: "Sales_Potential_of_village__c",
  SALES_POTENTIAL_CATEGORY__C: "sales_potential_category__c",
  X7_DAYS_VISIT_AFTER_DEMO__C: "X7_Days_Visit_after_Demo__c",
  X14_DAYS_VISIT_AFTER_DEMO__C: "X14_Days_Visit_after_Demo__c",
  X21_DAYS_VISIT_AFTER_DEMO__C: "X21_Days_Visit_after_Demo__c",
  EMPLOYEES_TO_BE_ADDED_FOR_TRAINING__C:
    "Employees_to_be_added_for_training__c",
  CLOSING_KMS__C: "Closing_kms__c",
  FARMER_PREFERRED_RETAILER__C: "Farmer_preferred_retailer__c",
  OPENING_KMS__C: "Opening_kms__c",
  FARMER_INTERESTED_IN_WHICH_PRODUCT__C:
    "Farmer_interested_in_which_product__c",
  PRODUCT_QUANTITY_LIQUIDATION_A__C: "Product_Quantity_Liquidation_A__c",
  PRODUCT_QUANTITY_LIQUIDATION_B__C: "Product_Quantity_Liquidation_B__c",
  PRODUCT_QUANTITY_LIQUIDATION_C__C: "Product_Quantity_Liquidation_C__c",
  FO_Name__c: "FO_Name__c",
  LPD_Date__c: "LPD_Date__c",
  Pest_Type_Picklist__c: "Pest_Type_Picklist__c",
  Area_of_Demostration__c: "Area_of_Demostration__c",
  Plot_Acreage__c: "Plot_Acreage__c",
  Severity__c: "Severity__c",
  Sowning_date__c: "Field_Sowing_date__c",
  Expected_harvest_date__c: "Expected_harvest_date__c",
  Dosage_per_acre__c: "Dosage_per_acre__c",
  Application_method__c: "Application_method__c",
  Demo_plot_size_acre__c: "Demo_plot_size_acre__c",
  Field_Sowing_date__c: "Field_Sowing_date__c",
  Field_Crop__c: "Field_Crop__c",
  Field_Name__c: "Field_Name__c",
  Field_Date__c: "Field_Date__c",
  Field_Activity__c: "Field_Activity__c",
  Field_Description__c: "Field_Description__c",
  Field_Plot_Area__c: "Field_Plot_Area__c",
  Field_Pest_Type__c: "Field_Pest_Type__c",
  Field_Brand__c: "Field_Brand__c",
  Field_Pest_Name__c: "Field_Pest_Name__c",
  Field_Severity__c: "Field_Severity__c",
  Field_Demo_Date__c: "Field_Demo_Date__c",
  Field_Expected_Harvest_date__c: "Field_Expected_Harvest_date__c",
  Field_Comments__c: "Field_Comments__c",
  Demo_Activity_Type__c: "Demo_Activity_Type__c",
  Visited_by__c: "Visited_by__c",
  Rating_for_demo_given_by_farmer__c: "Rating_for_demo_given_by_farmer__c",
  SUBJECT__C: "subject__c",
  COMPLAIN_TYPE__C: "complaint_type__c",
  STATUS__C: "status__c",
  Plot_Area__c: "Plot_Area__c",
  Sowing_date__c: "Sowing_date__c",
  PRODUCT_RATING_OVER_COMPETITION__C: "Product_rating_over_competition__c",
  COST_BENEFIT_TO_FARMER__C: "Cost_benefit_to_farmer__c",
  CUSTOMER_SATISFACTION__C: "Customer_satisfaction__c",
  EASE_OF_APPLICATION__C: "Ease_of_application__c",
  VALUE_DELIVERY_TO_CUSTOMER_ON_PRODUCT_US__C:
    "Value_delivery_to_customer_on_product_us__c",
  FARMER_USED_PRODUCT__C: "Farmer_used_product__c",
  Next_observation_Day__c: "Next_observation_Day__c",
  Event_Demo_LPD_Activity__c: "Event_Demo_LPD_Activity__c",
  ACTIVITY__C: "Activity__c",
  PEST_TYPE__C: "Pest_type__c",
  CREATED_DATE: "createddate",
  LAST_MODIFIED_DATE: "lastmodifieddate",
  Travel_Ticket_Amount__c: "Travel_Ticket_Allowance__c",
  Company_Vehicle_Maintenance_Amount__c:
    "Company_Vehicle_Maintenance_Amount__c",
  Postage_And_Courier__c: "Postage_And_Courier_Amount__c",
  Mobile_Bill__c: "Mobile_Bill_Amount__c",
  Toll_Tax__c: "Toll_Tax_Amount__c",
  Other_Miscellaneous__c: "Other_Miscellaneous__c",
  Other_Miscellaneous_Amount__c: "Other_Miscellaneous_Amount__c",
  Daily_Allowance_Amount__c: "Daily_Allowance_Amount__c",
  Outstation_Daily_Allowance_Amount__c: "Outstation_Daily_Allowance_Amount__c",
  Local_Conveyance_Amount__c: "Local_Conveyance_Amount__c",
  Select_Category__c: "Select_Category__c",
  Odometer_Start_Reading__c: "Odometer_Start_Reading__c",
  Odometer_End_Reading__c: "Odometer_End_Reading__c",
  Total_KM_Travelled__c: "Total_KM_Travelled__c",
  Fuel_Amount__c: "Fuel_Amount__c",
  Vehicle_Type__c: "Vehicle_Type__c",
  From_Date__c: "From_Date__c",
  To_Date__c: "To_Date__c",
  Total_Days__c: "Total_Days__c",
  Hotel_Bills__c: "Hotel_Bills__c",
  Miscellaneous_Amount__c: "Miscellaneous_Amount__c",
  Gross_Weight__c: "gross_weight__c",
  Std_Price__c: "std_price__c",
  AccountId: "AccountId",
  TotalAmount: "TotalAmount",
  Status: "Status",
  OrderNumber: "OrderNumber",
  OrderItemNumber: "OrderItemNumber",
  ORDER__C: "Order__c",
  Order__Heroku_ID__c: "Order__Heroku_ID__c",
  Quantity: "Quantity",
  TotalPrice: "TotalPrice",
  Product2Id: "Product2Id",
  Type__c: "Type__c",
  OBJECTID: "objectId",
  ON_FIELD__C: "On_Field__c",
  IIL_PRODUCT_PROMOTED__C: "IIL_Product_promoted__c",
  CONVERSION__C: "Conversion__c",
  PRODUCT_BOUGHT_FROM__C: "Product_Bought_From__c",
  PRODUCT_BOUGHT__C: "Product_Bought__c",
  Account__r__Heroku_ID__c: "Account__r__Heroku_ID__c",
  EffectiveDate: "EffectiveDate",
  Remarks__C: "remarks__c",
  Geo_Location__Latitude__s: "Geo_Location__Latitude__s",
  Geo_Location__Longitude__s: "Geo_Location__Longitude__s",
  Distributor__c: "Distributor__c",
  Retailer__c: "Retailer__c",
  STATUS: "status",
  user__c__Heroku_ID__c: "user__c__Heroku_ID__c",
  Amount_Achievement__c: "Amount_Achievement__c",
  Amount_Target__c: "Amount_Target__c",
  EMP_No__c: "EMP_No__c",
  Month__c: "Month__c",
  Invoice_Year__c: "invoice_year__c",
  Invoice_Month__c: "invoice_month__c",
  Invoice_Amount__c: "invoice_amount__c",
  Invoice_Quantity__c: "invoice_quantity__c",
  Invoice__c: "invoice__c",
  Owner__r__Heroku_ID__c: "Owner__r__Heroku_ID__c",
  Prod__c: "Prod__c",
  Product_Achivement__c: "Product_Achivement__c",
  Product_Category__c: "Product_Category__c",
  Year__c: "Year__c",
  Employee_ID__c: "employee_id__c",
  Pricebook2id: "pricebook2id",
  PricebookEntryId: "PricebookEntryId",
  LogoutStatus: "Log_Out_Status__c",
  LoginStatus: "login_status__c",
  Feedback_DistributorId: "Feedback_DistributorId",
  Feedback_RetailerId: "Feedback_RetailerId",
  Retailer_Account__c: "Retailer_Account__c",
  Distributor_Account__c: "Distributor_Account__c",
  Shop_Front_Pic__c: "Shop_Front_Pic__c",
  Counter_Front_Pic__c: "Counter_Front_Pic__c",
  Interested_in_Dealer_Board__c: "Interested_in_Dealer_Board__c",
  Image_of_Pest_Lic__c: "Image_of_Pest_Lic__c",
  Others__c: "Others__c",
  ID_Proof__c: "ID_Proof__c",
  Territory_Mapping__c: "territory_mapping__c",
  Territory_Mapping1__c: "territory_mapping1__c",
  Territory_Mapping2__c: "territory_mapping2__c",
  SI_REGION__C: "si_region__c",
  TEHSIL__C: "Tehsil__c",
  Si_Region__c: "si_region__c",
  Rm_Region__c: "rm_region__c",
  Amr_Region__c: "amr_region__c",
  Zm_Region__c: "zm_region__c",
  Cluster_region__c: "cluster_region__c",
  Last_Modified_By_Id: "LastModifiedById",
  Permanent_Address__c: "Permanent_residence_address__c",
  Present_Address__c: "Present_Residence_address__c",
  Father_Husband_Name__c: "Father_s_Husband_s_Name__c",
  Business_Owner_Mobile__c: "Mobile_Number__c",
  Business_Owner_Email__c: "Email_ID__c",
  Company_Existing_Business__c: "Name_of_Company_doing_existing_Business__c",
  Total_Dealing_Years__c: "No_of_Years_of_Dealing__c",
  Major_Product__c: "Major_Products__c",
  Annual_Turnover__c: "Annual_Turnover__c",
  Total_Dealers__c: "No_of_Dealers__c",
  Total_Credit_Days__c: "No_of_Credit_days__c",
  Cash_Or_Credit__c: "Cash_Credit__c",
  Product_Name__c: "Product_Name__c",
  Other_Products__c: "Others__c",
  Products_Unit__c: "Unit__c",
  Current_Fiscal_Year__c: "Current_Fiscal_Year_Quantity__c",
  Next_Fiscal_Year_Quantity__c: "Next_Fiscal_Year_Quantity__c",
  Next_Fiscal_Year_Unit__c: 'Next_Fiscal_Year_Unit__c',
  Next_Fiscal_Year__c: 'Next_Fiscal_Year__c',
  Sister_Company_Address__c: "Sister_Company_Address__c",
  Sister_Company_Turnover__c: "Sister_Company_Turnover__c",
  Credit_Period_Specify_No_of_Days__c: "Credit_Period_Specify_No_of_Days__c",
  Credit_Limit_Specify_Amount__c: "Credit_Limit_Specify_Amount__c",
  Creditibility_in_Market_for_Managers_O__c:
    "Creditibility_in_Market_for_Managers_O__c",
  Distributor_Approval_Status__c: "Distributor_Approval_Status__c",
  SAP_ID__c: "SAP_ID__c",
  IS_PARTIAL_FARMER__c: "Draft_Farmer__c",
  Plant_region__c: "Plant_region__c",
  Plant_description__c: "Plant_description__c",
  Other_specify__c: "Other_specify__c",
  Plant_Code__c: "Plant_Code__c",
  Material__c: "Material__c",
  Category_type__c: "Category_type__c",
  Product_disscussion__c: "Product_disscussion__c",
  New_Products_Discussion__c: "New_Products_Discussion__c",
  Focus_Products_Discussion__c: "Focus_Product_Discussion__c",
  Approach_For_Trial__c: "Approach_For_Trial__c",
  Results_Of_Trial__c: "Results_Of_Trial__c",
  Points__c: "Points__c",
  Purpose__c: "Purpose__c",
  Total_Points__c: "Total_Points__c",
  Plant_Master__c: "Plant_Master__c",
  Application_version_name__c: "Application_version_name__c",
  Device_Id__c: "Device_Id__c",
  Device_Name__c: "Device_Name__c",
  Device_OS_version__c: "Device_OS_version__c",
  Fcm_token__c: "Fcm_token__c",
  Platform_Name__c: "Platform_Name__c",
  HR_Policy_Profile__c: "HR_Policy_Profile__c",
  Group_ID__c: "Group_ID__c",
  Expense_Approver__c: "Expense_Approver__c",
  Expense_Line_Item__c: "Expense_Line_Item__c",
  Expense_Line_Item__r__Heroku_ID__c: "Expense_Line_Item__r__Heroku_ID__c",
  Expense_Line_Item__c__Heroku_ID__c: "Expense_Line_Item__c__Heroku_ID__c",
  Balance__c: "Balance__c",
  Closing_Balance__c: "Closing_Balance__c",
  Opening_Balance__c: "Opening_Balance__c",
  Party_Customer_Name_Station__c: "Party_Customer_Name_Station__c",
  Financial_Year__c: "Financial_Year__c",
  Credit__c: "Credit__c",
  Debit__c: "Debit__c",
  Description__c: "Description__c",
  Auto_Attendance_Marked__c: "Auto_Attendance_Marked__c",
  Approved_By__c: "Approved_By__c",
  isProduct__c: "isProduct__c",
  url__c: "url__c",
  IsDeleted: "IsDeleted",
  OTP__c: "otp__c",
  daily_allowance_status__c: "daily_allowance_status__c",
  outstation_daily_allowance_status__c: "outstation_daily_allowance_status__c",
  local_conveyance_status__c: "local_conveyance_status__c",
  fuel_status__c: "fuel_status__c",
  travel_tickets_status__c: "travel_tickets_status__c",
  company_vehicle_maintenance_status__c:
    "company_vehicle_maintenance_status__c",
  postage_courier_status__c: "postage_courier_status__c",
  mobile_bill_status__c: "mobile_bill_status__c",
  toll_tax_status__c: "toll_tax_status__c",
  others_status__c: "others_status__c",
  hotel_stay_status__c: "hotel_stay_status__c",
  MESSAGE_FOR: 'messageFor',
  MESSAGE_CREATED: 'createdAt',
  MESSAGE: 'message',
  MESSAGE_FROM: 'messageFrom',
  MESSAGE_TO: 'messageTo',
  MESSAGE_HEADER: 'header',
};
// ----------------------- all fields name ends here --------------------

//   ---------------------- api endpoints starts --------------------
const API_END_POINT = {
  GET_USER_TYPE: "getUserType",
  GET_OFFICERS_BY_TERRITORY: "getOfficersByTerritory",
  GET_MDM: "getMdm",
  GET_COMPANY_PERSONNEL: "getCompanyPersonnel",
  GET_VAN_CAMPAIGN_VILLAGES: "getVanCampaignVillages",
  ADD_FARMER_MAPPING_DETAILS: "addFarmerMappingDetails",
  GET_FARMER_MAPPING_DETAILS: "getFarmerMappingDetails",
  GET_FARMER_MAPPING_DETAILS_BY_ID: "getFarmerMappingDetailsById",
  UPDATE_FARMER_MAPPING_DETAILS_BY_ID: "updateFarmerMappingDetailsById",
  USER_LOGIN: "userLogin",
  USER_LOGOUT: "userLogout",
  VERIFY_OTP: "verifyOTP",
  GET_PROFILE: "getProfile",
  GET_COMPANIES_NAME: "getCompaniesName",
  ADD_AGRI_EXPERT_MAPPING_DETAILS: "addAgriExpertMappingDetails",
  GET_AGRI_EXPERT_MAPPING_DETAILS: "getAgriExpertMappingDetails",
  GET_AGRI_EXPERT_MAPPING_DETAILS_BY_ID: "getAgriExpertMappingDetailsById",
  UPDATE_AGRI_EXPERT_MAPPING_DETAILS_BY_ID:
    "updateAgriExpertMappingDetailsById",
  ADD_PICKLIST_CATEGORIES: "addPicklistCategories",
  GET_PICKLIST_CATEGORIES: "getPicklistCategories",
  ADD_PICKLIST: "addPicklist",
  GET_PICKLIST: "getPicklist",
  GET_PICKLIST_MASTER: "getPicklistMaster",
  GET_STATES: "getStates",
  GET_DISTRICTS: "getDistricts",
  GET_SUB_DISTRICTS: "getSubDistricts",
  UPDATE_ATTENDANCE_STATUS: "updateAttendanceStatus",
  ADD_RETAILER_MAPPING_DETAILS: "addRetailerMappingDetails",
  GET_RETAILER_MAPPING_DETAILS: "getRetailerMappingDetails",
  GET_RETAILER_MAPPING_DETAILS_BY_ID: "getRetailerMappingDetailsById",
  UPDATE_RETAILER_MAPPING_DETAILS_BY_ID: "updateRetailerMappingDetailsById",
  GET_DEPOTS_FOR_DISTRIBUTOR: "getDepotsForDistributor",
  ADD_DISTRIBUTOR_MAPPING_DETAILS: "addDistributorMappingDetails",
  GET_DISTRIBUTOR_MAPPING_DETAILS: "getDistributorMappingDetails",
  GET_DISTRIBUTOR_MAPPING_DETAILS_BY_ID: "getDistributorMappingDetailsById",
  UPDATE_DISTRIBUTOR_MAPPING_DETAILS_BY_ID:
    "updateDistributorMappingDetailsById",
  APPROVE_DISTRIBUTOR_MAPPING_DETAILS_BY_ID:
    "approveDistributorMappingDetailsById",
  GET_DISTRIBUTORS: "getDistributors",
  GET_RETAILERS: "getRetailers",
  GET_VILLAGES: "getVillages",
  GET_PICKLIST_BY_CATEGORY_ID: "getPicklistByCategogyId",
  ADD_VAN_CAMPAIGN_DETAILS: "addVanCampaignDetails",
  ADD_NEW_PRODUCT_TRAIL: "addNewProductTrail",
  GET_NEW_PRODUCT_TRAIL: "getNewProductTrail",
  GET_NEW_PRODUCT_TRAIL_BY_ID: "getNewProductTrailById",
  UPDATE_NEW_PRODUCT_TRAIL: "updateNewProductTrail",
  ADD_FARMER_MEETING_DETAILS: "addFarmerMeetingDetails",
  GET_FARMER_MEETING_DETAILS: "getFarmerMeetingDetails",
  GET_FARMER_MEETING_DETAILS_BY_ID: "getFarmerMeetingDetailsById",
  ADD_KVK_VISIT_DETAILS: "addKvkVisitDetails",
  GET_KVK_VISIT_DETAILS: "getKvkVisitDetails",
  GET_KVK_VISIT_DETAILS_BY_ID: "getKvkVisitDetailsById",
  ADD_DEMO_ACTIVITY: "addDemoActivity",
  GET_DEMO_ACTIVITY: "getDemoActivity",
  GET_DEMO_ACTIVITY_BY_ID: "getDemoActivityById",
  UPDATE_DEMO_ACTIVITY: "updateDemoActivity",
  ADD_BALOON_SHOW: "addBaloonShow",
  GET_BALOON_SHOW: "getBaloonShow",
  GET_BALOON_SHOW_BY_ID: "getBaloonShowById",
  EVENT_DETAILS: "getEventDetails",
  ADD_FARMER_VISIT: "addFarmerVisit",
  GET_FARMER_VISIT: "getFarmerVisit",
  GET_FARMER_VISIT_BY_ID: "getFarmerVisitById",
  UPDATE_FARMER_VISIT_BY_ID: "updateFarmerVisitById",
  GET_CROPS_FOR_FARMER: "getCropsForFarmer",
  GET_PRODUCTS_BY_CATEGORY_NAME: "getProductsByCategoryName",
  ASSIGN_TO: "assignTo",
  ADD_KRISHI_MELA: "addKrishiMela",
  GET_KRISHI_MELA: "getKrishiMela",
  GET_KRISHI_MELA_BY_ID: "getKrishiMelaById",
  ADD_RETAILER_VISIT: "addRetailerVisit",
  GET_RETAILER_VISIT: "getRetailerVisit",
  GET_RETAILER_VISIT_BY_ID: "getRetailerVisitById",
  UPDATE_RETAILER_VISIT_BY_ID: "updateRetailerVisitById",
  ADD_AGRIEXPERT_VISIT: "addAgriExpertVisit",
  GET_AGRIEXPERT_VISIT: "getAgriExpertVisit",
  GET_AGRIEXPERTS_DETAILS_BY_TYPE: "getAgriExpertsDetailsById",
  GET_AGRIEXPERT_VISIT_BY_ID: "getAgriExpertVisitById",
  GET_AGRIEXPERT_LAST_VISIT_BY_ID: "getAgriExpertLastVisitById",
  UPDATE_AGRIEXPERT_VISIT_BY_ID: "updateAgriExpertVisitById",
  ADD_DISTRIBUTOR_VISIT: "addDistributorVisit",
  GET_DISTRIBUTOR_VISIT: "getDistributorVisit",
  GET_DISTRIBUTOR_VISIT_BY_ID: "getDistributorVisitById",
  UPDATE_VAN_CAMPAIGN_DETAILS: "updateVanCampaignDetails",
  GET_VAN_CAMPAIGN_DETAILS: "getVanCampaignDetails",
  GET_VAN_CAMPAIGN_DETAILS_BY_ID: "getVanCampaignDetailsById",
  KNOW_MORE_DATA_VAN_CAMPAIGN_BY_ID: "knowMoreDataVanCampaignById",
  ADD_DEMO_LPD_ACTIVITY: "addDemoLpdActivity",
  GET_DEMO_LPD_ACTIVITY: "getDemoLpdActivity",
  GET_DEMO_LPD_ACTIVITY_BY_ID: "getDemoLpdActivityById",
  UPDATE_DEMO_LPD_ACTIVITY_BY_ID: "updateDemoLpdActivityById",
  ADD_DEMO_FIELD_DAY: "addDemoFieldDay",
  ADD_DEMO_OBSERVATION_DAY: "addDemoObservationDay",
  UPDATE_DEMO_FIELD_DAY_ACTIVITY: "updateDemoFieldDayActivity",
  UPDATE_DEMO_OBSERVATION_ACTIVITY: "updateDemoObservationActivity",
  UPDATE_EVENT_STATUS: "updateEventStatus",
  ADD_FARMER: "addFarmer",
  ADD_FEEDBACK: "addFeedback",
  GET_FEEDBACK: "getFeedback",
  UPDATE_FEEDBACK_STATUS: "updateFeedbackStatus",
  CREATE_EXPENSE: "createExpense",
  SUBMIT_EXPENSE: "submitExpense",
  SUBMIT_MULTIPLE_EXPENSE: "submitMultipleExpense",
  EDIT_EXPENSE: "editExpense",
  GET_EXPENSE: "getExpense",
  GET_EXPENSE_HISTORY: "getExpenseHistory",
  GET_EXPENSE_BY_DATE: "getExpenseByDate",
  GET_EXPENSE_TYPES: "getExpenseTypes",
  GET_EXPENSE_LIMIT: "getExpenseLimit",
  GET_EXPENSE_PENDING_APPROVAL: "getExpensePendingApprovalList",
  GET_EXPENSE_PENDING_APPROVAL_BY_ID: "getExpensePendingApprovalById",
  CHECK_EXPENSE_APPROVER_STATUS: "checkExpenseApprovalStatus",
  APPROVE_MASS_EXPENSE_PENDING_APPROVAL_BY_ID:
    "approveMassExpensePendingApprovalById",
  APPROVE_EXPENSE_PENDING_APPROVAL_BY_ID: "approveExpensePendingApprovalById",
  ADD_OTHERACTIVITY: "addOtherActivity",
  GET_OTHERACTIVITY: "getOtherActivity",
  GET_OTHERACTIVITY_BY_ID: "getOtherActivityById",
  GET_DISTRIBUTOR_ACCOUNTS_DETAILS: "getDistributorAccountsDetails",
  GET_DISTRIBUTORS_FOR_ORDER: "getDistributorsForOrder",
  GET_DEPOTS_FOR_ORDER: "getDepotsForOrder",
  GET_PRODUCTS_FOR_ORDER: "getProductsForOrder",
  GET_SFA_ORDERS_DETAILS: "getSfaOrdersDetails",
  GET_SFA_DISTRIBUTORS: "getSfaDistributors",
  GET_PRODUCT_CATEGORIES: "getProductCategories",
  GET_PRODUCTS: "getProducts",
  ORDER_PRODUCTS: "orderProducts",
  GET_ALL_ORDER_DETAILS: "getAllOrderDetails",
  GET_ORDER_DETAILS_BY_ID: "getOrderDetailsById",
  GET_Z8_EXPENSE_RECORDS: "getZ8ExpenseRecords",
  GET_DETAILS_BY_MOBILE: "getDetailsByMobile",
  GET_EVENT_DETAILS_BY_SFID: "getEventDetailsBySfid",
  GET_USER_DETAILS_BY_SFID: "getUserDetailsBySfid",
  MY_EVENTS: "myEvents",
  GET_Z8_EVENTS: "getZ8Events",
  Z8_APPROVE_EVENT: "approveZ8Event",
  GET_ALL_VILLAGES: "getAllVillages",
  DMS_USER_LOGIN: "dmsUserLogin",
  DMS_VERIFY_OTP: "dmsVerifyOTP",
  DMS_GET_PROFILE: "dmsGetProfile",
  DMS_ADD_SUGGESTION: "dmsAddSuggestion",
  ADD_FARMER_FOR_EVENT: "addFarmerForEvent",
  GET_FARMER_FOR_EVENT: "getFarmerForEvent",
  GET_PARTIAL_FARMERS: "getPartialFarmers",
  DMS_ORDER_PRODUCTS: "dmsOrderProducts",
  GET_ALL_ORDERS_BY_DMS: "getAllOrdersByDms",
  GET_ALL_ORDERS_BY_SFA_FOR_DMS: "getAllOrdersBySfaForDms",
  DMS_GET_ORDER_DETAILS_BY_ID: "dmsGetOrderDetailsById",
  DMS_ORDER_UPDATE: "dmsOrderUpdate",
  ADD_TARGET_LIST: "addTargetList",
  GET_PRODUCTS_FOR_TARGET_LIST: "getProductsForTargetList",
  GET_TARGET_LIST: "getTargetList",
  GET_ACHIEVEMENT_LIST: "getAchievementList",
  ADD_DMS_FEEDBACK: "addDmsFeedback",
  VALIDATE_FIELD: "validateField",
  SEARCH: "search",
  GET_FARMER_GLOBAL: "getFarmerGlobal",
  Get_Attendance_Status: "getAttendanceStatus",
  Get_Previous_Attendance_Status: "Get_Previous_Attendance_Status",
  Get_Previous_Attendance_Status_History: "getPreviousAttendanceStatusHistory",
  Get_Previous_Attendance_History_For_Approvel:
    "getPreviousAttendanceHistoryForApprovel",
  Update_Previous_Attendance_Status: "updatePreviousAttendanceStatus",
  Add_Previous_Attendance: "addPreviousAttendance",
  Check_Duplicate_GST: "checkDuplicateGST",
  GET_DRAFT_FARMERS: "getDraftFarmers",
  GET_DRAFT_FARMER_BY_ID: "getDraftFarmerById",
  GET_DRAFT_FARMERS: "getDraftFarmers",
  GET_DRAFT_FARMER_BY: "getDraftFarmerById",
  GET_HIERARCHY_WISE_REGION: "getHierarchyWiseRegion",
  GET_HIERARCHY_TEHSIL_REGION: "getHierarchyTehsilRegion",
  GET_HIERARCHY_DISTRICT_REGION: "getHierarchyDistrictRegion",
  GET_HIERARCHY_WISE_ALL: "getHierarchyWiseAll",
  GET_NOTIFICATIONS: "getNotifications",
  GET_NOTIFICATION_BY_ID: "getNotificationById",
  DISTRIBUTOR_RELATED_360: "distributorRelated360",
  GET_INVOICE_URL: "getInvoiceUrl",
  GET_LEADERBOARD_DATA: "getLeaderboardData",
  GET_LEDGER_DATA_DMS: "getLedgerDataDms",
  GET_ANNOUNCEMENTS: "getAnnouncements",
  GET_DIPOT_DATA: "getDipotData", // add rohit
};

// ------------------------ api endpoints ends ---------------------------

// --------------------- message starts --------------------
const MESSAGE = {
  INSERTED_SUCCESS: "created successfully",
  INSERTED_FAIL: "Insertion Failed",
  VANCAMPAIGNDETAILS: "Your campaign created successfully",
  VAN_CAMPAIGN_UPDATESUCCESS: "Van campaign executed successfully",
  VAN_CAMPAIGN_ALREADY_EXISTS: "Van campaign already exist",
  BALLOON_SHOW_CAMPAIGN_ALREADY_EXISTS: "Balloon show already exist",
  KRISHI_MELA_ALREADY_EXISTS: "Krishi mela already exist",
  FARMER_MEETING_ALREADY_EXISTS: "Farmer meeting already exist",
  KVK_VISIT_ALREADY_EXISTS: "KVK visit already exist",
  DEMOACTIVITYDETAILS: "Your demo activity created successfully",
  UNAUTHORIZEDACCESS: "Unauthorized access",
  MISSINGPARAMS: "Missing params",
  TURN_ON_LOCATION: "Please turn on your location",
  MISSING_HEADERS_PARAMS: "Missing header params",
  NO_AREA_MANAGER: "No area manager found",
  FETCHSUCCESS: "Fetched success",
  LOGINSUCCESS: "Login success",
  UPDATESUCCESS: "Updated success",
  UPDATEFAIL: "Update failed",
  SAVEFARMERDETAILS: "Farmer details created successfully",
  SAVE_RETAILER_DETAILS: "Retailer details created successfully",
  SAVE_FARMER_ONBOARDING_DETAILS:
    "Farmer Onboarding details created successfull",
  SAVE_FARMER_EVENT_DETAILS: "Farmer event  created successfull",
  SAVE_KVK_VISIT_DETAILS: "KVK Visit created sussessfull",
  SAVE_BALLOON_SHOW_DETAILS: "Balloon show created sussessfull",
  INVALID_USER: "User is not registered.",
  OTP_SEND_SUCCESS: "OTP Send Successfull",
  OTP_SEND_FAILD: "OTP note sended",
  INCORRET_USERNAME_PASSWORD: "Invalid username/password.",
  MOBILE_DUPLICATE: "Mobile number already exist.",
  DUPLICATE_PICKLIST_CATEGORIES: "Picklist category already exist.",
  DUPLICATE_PICKLIST: "Picklist already exist.",
  AADHAR_DUPLICATE: "Aadhar number already exist.",
  EMAIL_DUPLICATE: "Email already exist.",
  PAN_DUPLICATE: "Pan No. already exist.",
  GST_DUPLICATE: "Gst No. already exist.",
  GST_DOES_NOT_EXIST: "Gst No. does not exist.",
  INST_DUPLICATE: "Inst. Lic. No. already exist.",
  FERT_DUPLICATE: "Fert. Lic. No. already exist.",
  KVK_DUPLICATE: "KVK event already booked for the particular date.",
  INVALID_DATA_TYPE: "Invalid data type",
  DATA_NOT_FOUND: "Data not found",
  MOBILE_NOT_FOUND: "Mobile Number does not match",
  SOMETHING_WENT_WRONG: "Something went wrong.",
  MAXIMUM_EXPENSE_CLAIMING_DAYS_EXCEED:
    "Maximum expense claiming days has been exceeded",
  DAILY_ALLOWANCE_AND_OUTSTATION_DAILY_ALLOWANCE_ERROR:
    "Cannot pass daily allowance and outstation daily allowance at a same time.",
  DAILY_ALLOWANCE_ALREADY_EXISTS: "Daily allowance already created.",
  OUTSTATION_DAILY_ALLOWANCE_ALREADY_EXISTS:
    "Outstation daily allowance already created.",
  LOCAL_CONVEYANCE_ALREADY_EXISTS: "Local conveyance already exists.",
  LOCAL_CONVEYANCE_AND_OUTSTATION_CONFLICTS:
    "Local conveyance and Outstation daily allowance conflicts.",
  FUEL_ALREADY_EXISTS: "Fuel already exists.",
  HOTEL_STAY_ALREADY_EXISTS: "Hotel stay already exists.",
  MISCELLANEOUS_ALREADY_EXISTS: "Miscellaneous already exists.",
  SUGGESTION:
    "Suggestions are greatly appreciated vs suggestions will be greatly appreciated.",
  VALIDATION_SUCCESS: "Validation successfull",
  ALREADY_LOGGED_IN: "Already logged in",
  ALREADY_LOGGED_OUT: "Already logged out",
  EVENT_NOT_FOUND: "Event not found",
  ACCOUNT_ALREADY_EXIST: "Account already exist.",
  INVALID_DATE: "Invalid Date",
  PROFILE_NOT_FOUND: "Profile not found",
  ATTENDANCE_NOT_FOUND: "Attendance not found for this date",
  EXPENSE_ALREADY_CREATED: "Expense already created for this date",
  EXPENSE_APPROVED_OR_PENDING:
    "Expense already in pending or approved for this date",
  DA_ODA_LIMIT_EXCEED:
    "Daily allowance and outstation daily allowance limit exceeded",
};
// --------------------- message ends --------------------

// --------------------- sms starts --------------------

const STATIC_OTP = "898989";

const SMS_PARTY = {
  IIL: "IIL",
  MINOVO: "MINOVO",
};



const SMS_COUNTRY = {
  URL: "https://restapi.smscountry.com/v0.1/Accounts/JuDCjsaKdjuUVZJdBZYO/SMSes/",
  TOKEN:
    "Basic SnVEQ2pzYUtkanVVVlpKZEJaWU86cGI1WnlDc1pNdkZFSDI0dEFLY0Z0V1Y0VGgya3BaaHBGd3JmdU41SA==",
};
// --------------------- sms ends --------------------

// -------------------- user hierarchy starts --------------------
const USER_HIERARCHY = {
  SI__user: "SI",
  AM__user: "AM",
  RM__user: "RM",
  ZM__user: "ZM",
  VP_user: "VP",
  Finance_user: "Finance",
  Crop_Advisor_user: "Crop Advisor",
  Depot_Manager_user: "Depot Manager",
};

const DISTRIBUTOR_APPROVAL_STATUS = {
  SENT_FOR_APPROVAL_L2: 'Sent for Approval to L2',
  APPROVED_BY_L2: 'Approved by L2',
  REJECTED_BY_L2: 'Rejected by L2',
  APPROVED_BY_L3: 'Approved by L3',
  REJECTED_BY_L3: 'Rejected by L3',
  APPROVED_BY_L4: 'Approved by L4',
  REJECTED_BY_L4: 'Rejected by L4',
};
// -------------------- user hierarchy ends --------------------

const RECORDS_PER_PAGE = 20;

// --------------------- different status --------------------
const STATUS = {
  ACCEPTED: "Accepted",
  REJECTED: "Rejected",
  APPROVED: "Approved",
  PENDING: "Pending",
  RESOLVED: "Resolved",
  ON_HOLD: "On Hold",
};
// --------------------- different status ends --------------------

// --------------------- different expense types start --------------------

const EXPENSE_TYPE = {
  DAILY_ALLOWANCE: "dailyAllowance",
  OUTSTATION_DAILY_ALLOWANCE: "outstationDailyAllowance",
  LOCAL_CONVEYANCE: "localConveyance",
  FUEL: "fuel",
  HOTEL_STAY: "hotelStay",
  MISCELLANEOUS: "miscellaneous",
};
// --------------------- different expense types ends --------------------

// --------------------- different expense status start --------------------

const EXPENSE_STATUS = {
  DRAFT: "draft",
  PENDING: "pending",
  REJECTED: "rejected",
  APPROVED: "approved",
};
// --------------------- different expense status ends --------------------

// --------------------- Multiple notification starts --------------------

const NOTIFICATION_FOR = {
  SPECIFIC: "specific",
  ALL: "all",
  FARMERS: "farmers",
  DISTRIBUTORS: "distributors",
  RETAILERS: "retailers",
  AGRI_EXPERTS: "agri_experts",
};


// --------------------- moltiple notiications ends --------------------


const MAXIMUM_EXPENSE_CLAIMING_DAYS = 45;
const MAXIMUM_DA_ODA_DAYS = 26;

module.exports = {
  RECORD_TYPES,
  AGRI_EXPERT_TYPE,
  API_END_POINT,
  COMPANIES,
  SCHEMA,
  OBJECTKEYNAME,
  STATIC_OTP,
  SMS_PARTY,
  SMS_COUNTRY,
  MESSAGE,
  USER_HIERARCHY,
  RECORDS_PER_PAGE,
  STATUS,
  EXPENSE_TYPE,
  EXPENSE_STATUS,
  MAXIMUM_DA_ODA_DAYS,
  MAXIMUM_EXPENSE_CLAIMING_DAYS,
  NOTIFICATION_FOR,
  DISTRIBUTOR_APPROVAL_STATUS,
};
