const { client } = require("../../middleware/database/database");
const {
  USER_HIERARCHY,
  SCHEMA,
  OBJECTKEYNAME,
  RECORD_TYPES,
  RECORDS_PER_PAGE,
} = require("../../utilities/constants");
const distributorVisits = {
  getDistributorVisitDetails: async (
    searchField,
    distributorId,
    sfid,
    pageNumber,
    pageLimit
  ) => {
    try {
      let qry;

      if (searchField && searchField.length > 2 && !distributorId) {
        qry = `
      SELECT 
      ${OBJECTKEYNAME.AT_SHOP__C},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.MOBILE__C},
      ${SCHEMA.SALESFORCE.ACCOUNT}.${OBJECTKEYNAME.SFID},
      ${SCHEMA.SALESFORCE.ACCOUNT}.${OBJECTKEYNAME.Firm_Name__c},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.DISTRIBUTOR_SHOP_NAME__C},
      ${OBJECTKEYNAME.CURRENT_INVENTORIES__C},
      ${OBJECTKEYNAME.MARKET_INSIGHTS__C},
      ${OBJECTKEYNAME.COLLECTION_TARGET_DISCUSSION__C},
      ${OBJECTKEYNAME.SALES_TARGET_DISCUSSION__C},
      ${OBJECTKEYNAME.FOCUS_PRODUCT_DISCUSSION__C},
      ${OBJECTKEYNAME.MARKET_DEVELOPMENT__C},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.PICTURE__C},
      ${OBJECTKEYNAME.DISTRIBUTOR_FEEDBACK__C},
      ${OBJECTKEYNAME.COMPLAINT_ISSUES__C},
      ${OBJECTKEYNAME.COMMENTS__C}, 
      TO_CHAR(${SCHEMA.SALESFORCE.VISIT__C}.${
          OBJECTKEYNAME.CREATED_DATE
        }, 'YYYY-MM-DD') as ${OBJECTKEYNAME.CREATED_DATE},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.ID_TYPE__C},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.OWNER__C},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.HEROKU_ID__C},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.RECORD_TYPE}
      FROM ${SCHEMA.SALESFORCE.VISIT__C}
      LEFT JOIN ${SCHEMA.SALESFORCE.ACCOUNT} ON ${SCHEMA.SALESFORCE.ACCOUNT}.${
          OBJECTKEYNAME.SFID
        } = ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.ACCOUNT__C}
      WHERE
      (CAST(${SCHEMA.SALESFORCE.ACCOUNT}.${
          OBJECTKEYNAME.MOBILE__C
        } as TEXT) iLIKE '${searchField}%' OR ${SCHEMA.SALESFORCE.ACCOUNT}.${
          OBJECTKEYNAME.Firm_Name__c
        } iLIKE '${searchField}%')
      AND
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.OWNER__C} = '${sfid}'
      AND
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.RECORD_TYPE} = '${
          RECORD_TYPES.DISTRIBUTOR_VISIT
        }'
      ORDER BY ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.CREATED_DATE} DESC
      OFFSET (${pageNumber} - 1) * ${pageLimit ? pageLimit : RECORDS_PER_PAGE}
      LIMIT ${pageLimit ? pageLimit : RECORDS_PER_PAGE}
    `;
      } else {
        qry = `
      SELECT 
      ${OBJECTKEYNAME.AT_SHOP__C},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.MOBILE__C},
      ${SCHEMA.SALESFORCE.ACCOUNT}.${OBJECTKEYNAME.SFID},
      ${SCHEMA.SALESFORCE.ACCOUNT}.${OBJECTKEYNAME.Firm_Name__c},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.DISTRIBUTOR_SHOP_NAME__C},
      ${OBJECTKEYNAME.CURRENT_INVENTORIES__C},
      ${OBJECTKEYNAME.MARKET_INSIGHTS__C},
      ${OBJECTKEYNAME.COLLECTION_TARGET_DISCUSSION__C},
      ${OBJECTKEYNAME.SALES_TARGET_DISCUSSION__C},
      ${OBJECTKEYNAME.FOCUS_PRODUCT_DISCUSSION__C},
      ${OBJECTKEYNAME.MARKET_DEVELOPMENT__C},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.PICTURE__C},
      ${OBJECTKEYNAME.DISTRIBUTOR_FEEDBACK__C},
      ${OBJECTKEYNAME.COMPLAINT_ISSUES__C},
      ${OBJECTKEYNAME.COMMENTS__C}, 
      TO_CHAR(${SCHEMA.SALESFORCE.VISIT__C}.${
          OBJECTKEYNAME.CREATED_DATE
        }, 'YYYY-MM-DD') as ${OBJECTKEYNAME.CREATED_DATE},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.ID_TYPE__C},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.OWNER__C},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.HEROKU_ID__C},
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.RECORD_TYPE}
      FROM ${SCHEMA.SALESFORCE.VISIT__C}
      LEFT JOIN ${SCHEMA.SALESFORCE.ACCOUNT} ON ${SCHEMA.SALESFORCE.ACCOUNT}.${
          OBJECTKEYNAME.SFID
        } = ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.ACCOUNT__C}
      WHERE
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.OWNER__C} = '${sfid}'
      AND
      ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.RECORD_TYPE} = '${
          RECORD_TYPES.DISTRIBUTOR_VISIT
        }'
      ${
        distributorId &&
        "AND " +
          SCHEMA.SALESFORCE.VISIT__C +
          "." +
          OBJECTKEYNAME.ACCOUNT__C +
          " = '" +
          distributorId +
          "'"
      }
      ORDER BY ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.CREATED_DATE} DESC
      OFFSET (${pageNumber} - 1) * ${pageLimit ? pageLimit : RECORDS_PER_PAGE}
      LIMIT ${pageLimit ? pageLimit : RECORDS_PER_PAGE}
      `;
      }

      return await client.query(qry);
    } catch (error) {
      throw error;
    }
  },
  getDistributorVisitDetailsById: async (sfid, herokuId) => {
    try {
      const qry = `
            SELECT 
            ${OBJECTKEYNAME.AT_SHOP__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.MOBILE__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.DISTRIBUTOR_SHOP_NAME__C},
            ${SCHEMA.SALESFORCE.ACCOUNT}.${OBJECTKEYNAME.Firm_Name__c},
            ${SCHEMA.SALESFORCE.ACCOUNT}.${OBJECTKEYNAME.INST_LICENSE_NO__C},
            ${SCHEMA.SALESFORCE.ACCOUNT}.${OBJECTKEYNAME.CONTACT_PERSON__C},
            TO_CHAR( ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.CREATED_DATE}, 'YYYY-MM-DD') as visit_date,
            ${OBJECTKEYNAME.CURRENT_INVENTORIES__C},
            ${OBJECTKEYNAME.MARKET_INSIGHTS__C},
            ${OBJECTKEYNAME.COLLECTION_TARGET_DISCUSSION__C},
            ${OBJECTKEYNAME.SALES_TARGET_DISCUSSION__C},
            ${OBJECTKEYNAME.FOCUS_PRODUCT_DISCUSSION__C},
            ${OBJECTKEYNAME.MARKET_DEVELOPMENT__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.PICTURE__C},
            ${OBJECTKEYNAME.DISTRIBUTOR_FEEDBACK__C},
            ${OBJECTKEYNAME.COMPLAINT_ISSUES__C},
            ${OBJECTKEYNAME.COMMENTS__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.ID_TYPE__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.OWNER__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.HEROKU_ID__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.RECORD_TYPE},
            STRING_AGG(${SCHEMA.SALESFORCE.PRODUCT2}.${OBJECTKEYNAME.NAME}, ', ') as ${OBJECTKEYNAME.PRODUCT__C},
            STRING_AGG(CAST(${SCHEMA.SALESFORCE.NEW_PRODUCT__C}.${OBJECTKEYNAME.QUANTITY__C} AS VARCHAR), ', ') as ${OBJECTKEYNAME.QUANTITY__C}
            FROM ${SCHEMA.SALESFORCE.VISIT__C}
            LEFT JOIN ${SCHEMA.SALESFORCE.ACCOUNT} ON ${SCHEMA.SALESFORCE.ACCOUNT}.${OBJECTKEYNAME.SFID} = ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.ACCOUNT__C}
            LEFT JOIN ${SCHEMA.SALESFORCE.NEW_PRODUCT__C} ON ${SCHEMA.SALESFORCE.NEW_PRODUCT__C}.${OBJECTKEYNAME.VISIT__C__HEROKU_ID__C} = ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.HEROKU_ID__C}
          LEFT JOIN ${SCHEMA.SALESFORCE.PRODUCT2} ON ${SCHEMA.SALESFORCE.PRODUCT2}.${OBJECTKEYNAME.SFID} = ${SCHEMA.SALESFORCE.NEW_PRODUCT__C}.${OBJECTKEYNAME.PRODUCT__C}
            WHERE
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.OWNER__C} = '${sfid}'
            AND
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.HEROKU_ID__C} = '${herokuId}'
            AND
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.RECORD_TYPE} = '${RECORD_TYPES.DISTRIBUTOR_VISIT}'
            GROUP BY
            ${OBJECTKEYNAME.AT_SHOP__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.MOBILE__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.DISTRIBUTOR_SHOP_NAME__C},
            ${SCHEMA.SALESFORCE.ACCOUNT}.${OBJECTKEYNAME.INST_LICENSE_NO__C},
            ${SCHEMA.SALESFORCE.ACCOUNT}.${OBJECTKEYNAME.CONTACT_PERSON__C},
            ${OBJECTKEYNAME.CURRENT_INVENTORIES__C},
            ${OBJECTKEYNAME.MARKET_INSIGHTS__C},
            ${OBJECTKEYNAME.COLLECTION_TARGET_DISCUSSION__C},
            ${OBJECTKEYNAME.SALES_TARGET_DISCUSSION__C},
            ${OBJECTKEYNAME.FOCUS_PRODUCT_DISCUSSION__C},
            ${OBJECTKEYNAME.MARKET_DEVELOPMENT__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.PICTURE__C},
            ${OBJECTKEYNAME.DISTRIBUTOR_FEEDBACK__C},
            ${OBJECTKEYNAME.COMPLAINT_ISSUES__C},
            ${OBJECTKEYNAME.COMMENTS__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.CREATED_DATE},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.ID_TYPE__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.OWNER__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.HEROKU_ID__C},
            ${SCHEMA.SALESFORCE.VISIT__C}.${OBJECTKEYNAME.RECORD_TYPE},
            ${SCHEMA.SALESFORCE.ACCOUNT}.${OBJECTKEYNAME.Firm_Name__c}
          `;
      return await client.query(qry);
    } catch (error) {
      throw error;
    }
  },
};
module.exports = {
  distributorVisits,
};
